In [2]:
import numpy as np

import matplotlib.pyplot as plt
import importlib

import findatree.io as io
import findatree.interactive as interactive
import findatree.geo_to_image as geo_to_image
import findatree.segmentation as segmentation
import findatree.object_properties as obj_props

from bokeh.plotting import show, save
from bokeh.io import output_notebook, output_file
# output_file(r'C:\Users\flori\Documents\prof\lwf\plots\220628\tnr11878.html')
output_notebook()

Loading BokehJS ...

### Load channels

In [3]:
importlib.reload(geo_to_image)

dir_names=[]
dir_names.extend([r'C:\Data\lwf\DSM_2021'])
dir_names.extend([r'C:\Data\lwf\DTM'])
dir_names.extend([r'C:\Data\lwf\Orthophotos_2021'])
dir_names.extend([r'C:\Data\lwf\CrownDelineation_2020'])

params_channels = {
    'tnr': 11048,
    'px_width_reproject': 0.2,
    'downscale': 0,
}

channels, params_channels = geo_to_image.channels_load(dir_names, params_channels)
io.channels_to_hdf5(channels, params_channels)

-----------
Parameters:
  date_time                     : 220705-103937
  tnr                           : 11048
  path_dsm                      : C:\Data\lwf\DSM_2021\Tnr_11048_D-20210707_DSM.tif
  path_dtm                      : C:\Data\lwf\DTM\tnr_11048_dtm.tif
  path_ortho                    : C:\Data\lwf\Orthophotos_2021\Tnr_11048_2021_Ortho.tif
  crs                           : EPSG:25832
  px_width_reproject            : 0.2
  downscale                     : 0
  px_width                      : 0.2
  shape                         : (1834, 1052)
  affine                        : [[ 2.00000000e-01  0.00000000e+00  6.46775586e+05]
 [ 0.00000000e+00 -2.00000000e-01  5.44620572e+06]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


### Load ground-truth shapes

In [54]:
importlib.reload(io)

polys, poly_attrs, params_shapes = io.load_shapefile(dir_names, params_channels)

1 (13, 2)
2 (13, 2)
3 (13, 2)
4 (13, 2)
5 (14, 2)
6 (14, 2)
7 (13, 2)
8 (13, 2)
9 (14, 2)
10 (13, 2)
11 (14, 2)
12 (13, 2)
13 (13, 2)
14 (13, 2)
15 (14, 2)
16 (14, 2)
17 (13, 2)
18 (13, 2)
19 (13, 2)
20 (13, 2)
21 (13, 2)
22 (13, 2)
23 (13, 2)
24 (13, 2)
25 (13, 2)
26 (13, 2)
27 (13, 2)
28 (13, 2)
29 (13, 2)
30 (13, 2)
31 (14, 2)
32 (13, 2)
33 (14, 2)
34 (13, 2)
35 (13, 2)
36 (13, 2)
37 (13, 2)
38 (14, 2)
39 (13, 2)
40 (14, 2)
41 (13, 2)
42 (13, 2)
43 (14, 2)
44 (13, 2)
45 (13, 2)
46 (13, 2)
47 (12, 2)
{'enr': 1, 'bnr': 1, 'ba': 134, 'bhd_2020': 489, 'alter_2020': 108.0, 'bk': 0, 'kkl': 1.0, 'nbv': 20.0, 'sst': 1.0, 'gilb': 0.0, 'kommentar': '', 'sicherheit': ''}
{'tnr': '11048', 'affine': array([[ 2.00000000e-01,  0.00000000e+00,  6.46775586e+05],
       [ 0.00000000e+00, -2.00000000e-01,  5.44620572e+06],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]), 'path_shapes': 'C:\\Data\\lwf\\CrownDelineation_2020\\Tnr_11048_Kr.shp', 'n_shapes': 47, 'n_attrs': 12, 'attrs_names': 

In [31]:
polys = load_shapefile(dir_names, params_channels)
polys[1]

(array([585.08054776, 592.22431205, 597.64828123, 597.64828123,
        596.06077805, 588.40230432, 577.93678347, 565.74713704,
        565.36905001, 558.62216152, 559.94508082, 575.82011258,
        585.08054776]),
 array([1272.26093391, 1273.18697742, 1279.93386593, 1284.56408352,
        1289.45888498, 1294.60720439, 1300.43911527, 1294.93447584,
        1286.94533829, 1280.06615787, 1274.64218868, 1272.52551778,
        1272.26093391]))

In [4]:
import shapefile
import pprint

importlib.reload(io)

# Get paths
paths = io._find_paths_in_dirs(dir_names, params_channels['tnr'])

sf = shapefile.Reader(paths['path_shapes'])

print(f"{'GEOJSON format:':<30} {sf.__geo_interface__['type']}")
print(f"{'No. of shapes':<30} {len(sf)}")
print(f"{'Shape type:':<30} {sf.shapeTypeName}")
print()
print(f"{'No. of records':<30} {len(sf.records())}")

field_names = [f[0] for f in sf.fields[1:]]
print(f"{'No. of field names per record:':<30} {len(field_names)}")
print(f"{'No. of attributes per record:':<30} {len(sf.record(4))}")

print('Attribute names:')
pp = pprint.PrettyPrinter(width=41, compact=True, indent=5)
pp.pprint(field_names)

print(sf.record(4))
print(np.array(sf.shape(1).points))
print(np.array(sf.shape(1).points).T)

GEOJSON format:                FeatureCollection
No. of shapes                  47
Shape type:                    POLYGON

No. of records                 47
No. of field names per record: 33
No. of attributes per record:  33
Attribute names:
[    'OBJECTID_1', 'OBJECTID', 'Field1',
     'fid_', 'Tnr', 'Sat', 'Enr', 'Bnr',
     'Ba', 'BHD_2020', 'Alter_2020',
     'BK', 'KKL', 'NBV', 'SST', 'Gilb',
     'Azi', 'Hori', 'utmx', 'utmy',
     'x_utm', 'y_utm', 'BUFF_DIST',
     'ORIG_FID', 'Shape_Leng',
     'Shape_Le_1', 'Shape_Area',
     'InPoly_FID', 'SimPgnFlag',
     'MaxSimpTol', 'MinSimpTol',
     'Kommentar', 'Sicherheit']
Record #4: [5984, 5984, 5983, 5983, 11048, 0, 1, 9, 134, 376, 108.0, 0, 2.0, 25.0, 1.0, 0.0, 230.0, 745, 646891.96, 5445952.747, 646888.577771, 5445946.109, 2.5, 5983, 15.7079632679, 15.516197449, 18.6891722141, 5983, 1, 0.2, 0.2, '', '']
[[ 646893.42506642 5445946.90458895]
 [ 646896.24512955 5445948.36621446]
 [ 646896.13400433 5445947.03271179]
 [ 646896.85777

### Segmentation

#### (1) Parametrized Segmentation

In [3]:
importlib.reload(segmentation)

params_segments = {
    # 'thresh_blur': True,
    # 'thresh_width':30,
    # 'thresh_downscale': 2,
    # 'water_channel':'chm',
    # 'water_hole_min_area': 0.2,
}

segments, params_segments = segmentation.segment(
    channels,
    params_channels,
    params_segments,
)
io.segments_to_hdf5(segments, params_segments)

-----------
Parameters:
  date_time                     : 220630-135857
  thresh_blur                   : False
  thresh_channel                : light
  thresh_downscale              : 1
  thresh_global_chm             : 5
  thresh_global_ndvi            : 0.4
  thresh_px_width               : 0.4
  thresh_shape                  : (917, 526)
  thresh_width                  : 30
  tnr                           : 11048
  water_channel                 : light
  water_downscale               : 0
  water_hole_min_area           : 0.0
  water_label_min_area          : 0.2
  water_peak_dist               : 1.2
  water_px_width                : 0.2
  water_shape                   : (1834, 1052)


#### (2) Plot segmentation results

In [29]:
importlib.reload(interactive)

plt = interactive.Plotter()
plt.width = 600
plt.channels_downscale = 1

plt.add_channels(channels, params_channels)
plt.add_segments(segments)

plt.figures_add_rgb()
plt.figures_add_gray('chm')

layout = plt.create_layout()

In [ ]:
show(layout)

### Object properties
#### (1) Extract object properties

In [6]:
# importlib.reload(obj_props)
# props, names = obj_props.labels_to_props_all(cs_segment['labels'], cs, params_cs, include_labels=None)

In [7]:
# # print(names)

# xlim = [5e-3, 1]

# # Filter
# name = 'perc75_chm'
# positives = props[:, names.index(name)]
# positives = positives > 5

# select = [
#     'perc75_blue',
#     'perc75_green',
#     'perc75_red',
#     'perc75_re',
#     'perc75_nir',
#     ]

# # select = [
# #     'mean_upperl_blue',
# #     'mean_upperl_green',
# #     'mean_upperl_red',
# #     'mean_upperl_re',
# #     'mean_upperl_nir',
# #     ]

# # bins = np.linspace(0.5,1,70)
# bins= 50


# f, ax = plt.subplots(figsize=[4,3])
# for name in select:
#     _ = ax.hist(
#         props[:, names.index(name)][positives],
#         bins=bins,
#         histtype='step',
#         label=name,
#         )

# _ = ax.legend(loc='upper left',bbox_to_anchor=(1,1))
# # ax.set_xlim(xlim)
# # ax.set_xscale('log')

In [8]:
# # print(names)

# # Filter
# name = 'perc75_chm'
# positives = props[:, names.index(name)]
# positives = positives > 5

# # Variables
# name1 = 'std_ndre'
# feature1 = props[:, names.index(name1)]

# name2 = 'perc75_chm'
# feature2 = props[:, names.index(name2)]

# name3 = 'perc75_s'
# feature3 = props[:, names.index(name3)]

# x = feature1[positives]
# y = feature2[positives]
# z = feature3[positives]

# f, ax = plt.subplots(figsize=[4,3])
# _ = ax.scatter(
#     x,
#     y,
#     # c=z,
#     color='k',
#     s=5,
#     alpha=0.5,
#     )

# ax.set_xlabel(name1)
# ax.set_ylabel(name2)